#version: '0.1'

services:
  chroma_sql:
    image: chromadb/chroma:1.5.9.dev44
    container_name: chroma_sql
    restart: always
    environment:
      # Tell Chroma where to save the data
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - ./DATABASE:/data
  
  rag_qa_project:
    build: .
    container_name: rag_qa_project
    restart: always
    depends_on:
      - chroma_sql